import type { Config } from 'tailwindcss';

export default {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        'deep-teal': {
          50: 'var(--deep-teal-50)',
          100: 'var(--deep-teal-100)',
          200: 'var(--deep-teal-200)',
          300: 'var(--deep-teal-300)',
          400: 'var(--deep-teal-400)',
          500: 'var(--deep-teal-500)',
          600: 'var(--deep-teal-600)',
          700: 'var(--deep-teal-700)',
          800: 'var(--deep-teal-800)',
          900: 'var(--deep-teal-900)',
          950: 'var(--deep-teal-950)',
        },
        'tamarind': {
          50: 'var(--tamarind-50)',
          100: 'var(--tamarind-100)',
          200: 'var(--tamarind-200)',
          300: 'var(--tamarind-300)',
          400: 'var(--tamarind-400)',
          500: 'var(--tamarind-500)',
          600: 'var(--tamarind-600)',
          700: 'var(--tamarind-700)',
          800: 'var(--tamarind-800)',
          900: 'var(--tamarind-900)',
          950: 'var(--tamarind-950)',
        },
        'shark': {
          50: 'var(--shark-50)',
          100: 'var(--shark-100)',
          200: 'var(--shark-200)',
          300: 'var(--shark-300)',
          400: 'var(--shark-400)',
          500: 'var(--shark-500)',
          600: 'var(--shark-600)',
          700: 'var(--shark-700)',
          800: 'var(--shark-800)',
          900: 'var(--shark-900)',
          950: 'var(--shark-950)',
        },
        'clinker': {
          50: 'var(--clinker-50)',
          100: 'var(--clinker-100)',
          200: 'var(--clinker-200)',
          300: 'var(--clinker-300)',
          400: 'var(--clinker-400)',
          500: 'var(--clinker-500)',
          600: 'var(--clinker-600)',
          700: 'var(--clinker-700)',
          800: 'var(--clinker-800)',
          900: 'var(--clinker-900)',
          950: 'var(--clinker-950)',
        },
        'bush': {
          50: 'var(--bush-50)',
          100: 'var(--bush-100)',
          200: 'var(--bush-200)',
          300: 'var(--bush-300)',
          400: 'var(--bush-400)',
          500: 'var(--bush-500)',
          600: 'var(--bush-600)',
          700: 'var(--bush-700)',
          800: 'var(--bush-800)',
          900: 'var(--bush-900)',
          950: 'var(--bush-950)',
        },
        'revolver': {
          50: 'var(--revolver-50)',
          100: 'var(--revolver-100)',
          200: 'var(--revolver-200)',
          300: 'var(--revolver-300)',
          400: 'var(--revolver-400)',
          500: 'var(--revolver-500)',
          600: 'var(--revolver-600)',
          700: 'var(--revolver-700)',
          800: 'var(--revolver-800)',
          900: 'var(--revolver-900)',
          950: 'var(--revolver-950)',
        },
        'azure-radiance': {
          50: 'var(--azure-radiance-50)',
          100: 'var(--azure-radiance-100)',
          200: 'var(--azure-radiance-200)',
          300: 'var(--azure-radiance-300)',
          400: 'var(--azure-radiance-400)',
          500: 'var(--azure-radiance-500)',
          600: 'var(--azure-radiance-600)',
          700: 'var(--azure-radiance-700)',
          800: 'var(--azure-radiance-800)',
          900: 'var(--azure-radiance-900)',
          950: 'var(--azure-radiance-950)',
        },
        'blue-violet': {
          50: 'var(--blue-violet-50)',
          100: 'var(--blue-violet-100)',
          200: 'var(--blue-violet-200)',
          300: 'var(--blue-violet-300)',
          400: 'var(--blue-violet-400)',
          500: 'var(--blue-violet-500)',
          600: 'var(--blue-violet-600)',
          700: 'var(--blue-violet-700)',
          800: 'var(--blue-violet-800)',
          900: 'var(--blue-violet-900)',
          950: 'var(--blue-violet-950)',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;
