name: 🌎 [i18n] Translation Issue
description: Report a translation issue.
title: '[i18n]: {Title}'
labels:
  - 'scope: i18n'

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this translation report!
  - type: textarea
    attributes:
      label: Description
      placeholder: >-
        A clear and concise description of what the translation issue is about and in which screen we can find it.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: >-
        Steps to reliably reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      placeholder: >-
        Any other context or considerations about the bug...

  - type: textarea
    attributes:
      label: Screenshots
      placeholder: >-
        Please provide relevant screenshots or screen recordings...
    validations:
      required: true

  - type: checkboxes
    id: new-translationissue
    attributes:
      label: Is there an existing translation issue for this?
      description: Please search to see if an issue already exists for the translation issue you encountered.
      options:
        - label: I have searched the existing issues
          required: true
