blank_issues_enabled: true
contact_links:
  - name: ScribbleLab Comunity
    url: https://discord.gg/Y5mUJbNC8h
    about: Connect with our developers and other community members
  - name: Frequently Asked Questions (FAQ)
    url: https://github.com/ScribbleLabApp/docs/tree/main
    about: Find answers to common questions
