blank_issues_enabled: true
contact_links:
  - name: ScribbleLab Comunity
    url: https://discord.gg/Y5mUJbNC8h
    about: Connect with our developers and other community members
  - name: ScribbleLabApp Support
    url: 
    about: Request a ticket for support